### ISSUE TITLE
syscall 추가를 어떻게 해야하나요?

### ISSUE THREAD

**Issue by qwerty3535** [ossnu/osfall2017#10]
지금까지 아래 링크를 통해서 구현해보려 했습니다.

https://limenote.net/@sangmoonpark/40/tizen-os-kernel-%EC%97%90-system-call-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

위의 링크를 비롯해서 여러가지 시도해봤는데 syscall 버전의 helloworld printk 가 출력되지 않습니다.

test main에서 printf를 하면 출력이 되는데 syscall추가하는 방법에 문제가 있는거 같습니다.

혹시 artik같은 경우에는 syscall 추가하는 방법이 다르거나 arm이 아닌 다른 arch를 사용하는 것인가요?

**Comment by pjbear1215** [comment]
다르지 않습니다. ARM 아키텍처를 사용합니다.

1. `helloworld.c`를 위 링크에 따라서 커널 컴파일할 때 같이 잘 컴파일하고
2. 컴파일된 커널 이미지를 artik에 업로드한 후, artik을 해당 커널로 재부팅하고
3. 호스트 컴퓨터에서 test.c 파일을 cross compile 해줘야 합니다. [[Compiling test program]](https://github.com/ossnu/osfall2017/blob/master/doc/Project1.md#compiling-test-program)
4. 그리고 컴파일된 test 실행파일을 artik에 push하신 후에
5. 호스트 컴퓨터에서 `sdb shell`을 통해 artik에 접근하신 뒤에 해당 test 실행파일을 실행시키시면 됩니다.
6. `printk`의 경우 콘솔창에 바로 보이지 않을 수 있으므로, `dmesg | tail` 명령어로 debug message를 출력해보시기 바랍니다.
