### ISSUE TITLE
기기 관련 문의입니다.

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#11]
조교님 안녕하세요?
![err](https://user-images.githubusercontent.com/27335809/30872748-1bf2955e-a326-11e7-8264-2194a4788ccb.png)
위와 같은 문제가 계속 반복되어서 테스트에 어려움을 겪고 있습니다.
기기 온도가 높다거나 참조할 수 없는 영역의 메모리를 참조한다는 메시지도 계속 뜹니다.
어떻게 해결할 수 있는지 여쭤보고 싶습니다.
감사합니다.

**Comment by pjbear1215** [comment]
기존 디폴트 커널 이미지를 artik에 올린 상태에서 저런 메시지가 뜨는 건가요?
기기 온도가 높아지는 문제는 저희도 해결방법을 찾지 못하였습니다.
진행이 불가능할 정도라면 기계를 교체해드릴테니 302동 319-1호로 방문해주시기 바랍니다.

**Comment by yksnen11** [comment]
57번에서 50번으로 교체했습니다.
감사합니다.
