### ISSUE TITLE
process의 list는 어떻게 접근할 수 있나요?

### ISSUE THREAD

**Issue by bigkunzi** [ossnu/osfall2017#12]
os-team7 입니다.
조교님께서 올려주신 https://github.com/ossnu/osfall2017/blob/master/doc/Project1.md 의 글을 보면 process가 double linked-list로 구현되어 있다고 하셨는데 이 linked-list에 어떻게 접근할 수 있을지 궁금합니다.

그리고 그 접근을 할 때
read_lock (&tasklist_lock);
read_unlock (&tasklist_lock);

을 해주라고 나와있는데, 이 tasklist_lock 이라는 것이 따로 선언할 필요가 없는 것인지 궁금합니다.

전반적으로 어려운 점은 무엇이 어디에 어떻게 정의되어 있는지 모르는 점 인 것 같습니다.

혹 다른 팀들은 어떻게 하고 있는지 모르겠지만, 진행 방법이 있다면 공유해주시면 도움이 많이 될 것 같습니다.

감사합니다.

**Comment by RockyLim92** [comment]
*include/linux/sched.h* 에서 *struct task_struct* 의 형태로 프로세스의 메타데이터를(pid, parent_pid 등등) 관리하고 있으니 참고하시면 좋을 것 같습니다.

**Comment by pjbear1215** [comment]
현재 사용하고 계신 IDE가 무엇인지는 모르겠지만, 저의 경우 `vim`을 사용합니다. 

`ctags`와 `cscope` 플러그인을 설치/활용하면 소스코드 분석을 쉽게 하실 수 있습니다. 

반드시 `vim`을 사용하실 필요는 없고, 편하신 IDE를 사용해서 소스코드를 분석하시면 될 것 같습니다. 

아마 웬만한 것들은 google에 검색하면 커널의 어느 위치에 정의되어 있는지 나올 것입니다.

그리고 `vim`, `ctags`, `cscope`도 구글링해보면 많은 자료들이 있으니 한번 찾아보시면 좋을 것 같습니다.
