### ISSUE TITLE
Proj2 질문

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#16]
안녕하세요?
`sched_setweight`와 `sched_getweight`를 `kernel/sched.c` 대신에 `kernel/sched/core.c`에 구현해도 되나요?
감사합니다.

**Comment by pjbear1215** [comment]
`kernel/sched/core.c`에 구현해야하는 특별한 이유가 있나요? 그런게 아니라면 spec에 따라서 `kernel/sched.c`에 구현해주시는게 좋을 것 같습니다.

**Comment by yksnen11** [comment]
네 감사합니다.
`core.c`에 시스템콜이 많이 구현되어 있어서 그 밑에다가 추가했었는데 특별한 이유가 없으니까 조교님 말씀대로 `sched.c`으로 옮기는 게 좋을 것 같습니다!
그런데 `init_task.h`와 `kthread.c`에서 policy를 SCHED_WRR로 바꾸니까 부팅 도중 멈추는데, 이런 경우 제 `wrr.c`에 문제가 있는 것이죠? 혹시 `rt.c` `fair.c`도 건드려야 하는 것은 아닌지 여쭤보고 싶습니다. 너무 양이 방대해서 여쭤보고자 합니다.
마지막으로, 중요한 사항은 아닙니다만 제공해주신 pdf에 있는 `kernel/sched.c`는 원래 코드에는 없고 대신 `core.c`가 그 역할을 하고 있는 것 같습니다. 이 점은 그냥 무시해도 되는 것이죠?
감사합니다.

**Comment by newspring97** [comment]
현재 저희가 사용하고 있는 커널 버전 3.10에서는 2.6버전과는 달리 kernel/sched.c와 kernel/sched_fair.c가 kernel/sched/ 폴더에 각각 core.c와 fair.c로 정의되어 있습니다.
그렇다면 kernel/sched.c를 새로 파일을 만들어서 구현하지 않고 kernel/sched/core.c에 시스템콜을 추가하여도 문제가 없을 것 같은데 core.c에 구현해도 무방하겠죠?

**Comment by pjbear1215** [comment]
확인해보니 제가 예전에 진행했었던 3.0 버전이랑 파일 위치가 많이 바뀌었네요.
@newspring97  님께서 말씀하신대로 구현하시면 됩니다. 
해당 내용은 프로젝트 2 설명에 반영 후 재공지하도록 하겠습니다.
혼란을 드려서 죄송합니다.

**Comment by pjbear1215** [comment]
@yksnen11 커널은 스케줄러쪽이 abstraction이 잘되어있어서 다른 스케줄링 policy를 건드릴 필요는 없을 것 같습니다. 힌트를 하나 드리자면, 돌아가는 코드를 만들기 위해서 반드시 scheduler abstraction의 모든 함수를 구현할 필요는 없습니다. `rt.c`나 `fair.c`를 뼈대로 시작하여 필요없는 부분들을 걷어내고 돌아가는 최소한의 버전을 만든 후, 거기다가 wrr의 기능을 추가하는 방식으로 접근하시는 것을 추천드립니다.
