### ISSUE TITLE
cpu 순회 구현에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by qwerty3535** [ossnu/osfall2017#18]
안녕하세요. OS 11조 박정원입니다.

스케줄링을 할 때 모든 cpu들을 순회해서 각 cpu rq안에 있는 값들을 비교해보려고 하는데

cpu 순회를 어떻게 구현해야할지 모르겠습니다.

찾아보니 for_each_online_cpu(cpu)로 하라는 것도 있었지만  get_online_cpus(); put_online_cpus(); 와 같은 Lock을 같이 쓰라고 되어있어 꺼림칙하고 

fair.c 에서 can_migrate_task function에서는 
cpumask_copy(cpus, cpu_active_mask); 와
struct lb_env env = {
...
.dst_grpmask    = sched_group_cpus(sd->groups),
...
}; 를 한 뒤에

for_each_cpu_and(cpu, env->dst_grpmask, env->cpus) 를 쓰는 거 같은데

env->dst_grpmask 가 무엇을 의미하는지 몰라서 제가 원하는 동작을 해줄지 모르겠습니다.

어떤 것을 써야 제가 원하는 대로 순회를 할 수 가 있나요?

아니면 다른 방법을 써야하는 것인지 알고 싶습니다.

**Comment by pjbear1215** [comment]
제가 확인해보니 어차피 `for_each_online_cpu(cpu)`가 `for_each_cpu(cpu, cpu_online_mask)`를 호출하도록 되어있습니다. 

`for_each_cpu_and`랑 `for_each_cpu`는 실제로 거의 다른게 없고, 하나의 bit mask를 더 추가해서 체크를 한번 더하는 식으로 되어있습니다. 

bit mask의 각 bit를 순서대로 체크하면서 해당 bit가 0이면 skip하고 넘어가는데, `for_each_cpu_and`의 경우 bit mask가 2개여서 각각의 bit mask의 bit가 모두 1일 때만 skip하지않는다는 점만 다릅니다.

`dst_grpmask`의 경우 destination group mask의 약자인 것으로 보입니다만, 현재 하려는 CPU 순회에서는 필요하지 않은 mask값인 것 같습니다.

`for_each_online_cpu(cpu)`를 쓰시면 될 것 같습니다. 

`get/put_online_cpus`는 CPU Hot plug 기능 때문에 필요한데 장치가 켜져있는 중에 CPU를 offline/online으로 변경이 가능하기 때문입니다.

Project 1에서 `task_list_lock`을 잡고 list_head를 traverse 했던 것과 비슷하다고 생각하시면 됩니다.
