### ISSUE TITLE
proj3 질문

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#27]
안녕하세요 조교님 1팀 이승현입니다.

"If a process wants to grab a lock for a range which does not cover the current physical device rotation, the process should block **until the device is rotated into that range**" 부분과 관련해서 여쭤보고 싶습니다.

어떤 writer A가 range [30 90]에 대해 lock을 잡고 있는 상황이고, current device rotation이 120이라고 해보겠습니다. range가 [30 90]인 어떤 reader B가 lock을 잡으려고 해서 일단 sleep시킨 다음에, current rotation이 60으로 바뀌었다면,

1) reader B를 wake 시켜줘야 하는 건가요?
2) writer A가 unlock하고 B가 lock을 잡을 수 있을 때 wake 시켜도 되는 건가요?

감사합니다.

**Comment by pjbear1215** [comment]
deadlock에 빠지는 위험을 막으려면 디자인을 최대한 단순화해야합니다. 디자인하실 때 state machine을 그려서 한번 생각해보세요.
(e.g. blocking 상태에 있던 프로세스는 반드시 waiting 상태로 바뀌고나서 자신이 lock을 잡을 순서가 됐을 경우에만 wake...)

reader B가 wake해봤자 lock을 잡을 수 없는걸 알 수 있는 상황이라면, 바로 깨우지말고 waiting list에 달아놓고 모든 조건이 만족했을 경우에만 wake 시키는 방법이 효율적일 것 같네요.
(__Hint__: 커널에서 제공하는 여러 자료구조들을 잘 활용해보세요)

즉, 말씀하신 2번처럼 프로세스가 wake했을 때 lock을 실제로 잡을 수 있는 경우에만 wake시키도록 구현하시는게 좋을 것 같습니다.

**Comment by yksnen11** [comment]
감사합니다!
