### ISSUE TITLE
기기 온도관련 문의입니다.

### ISSUE THREAD

**Issue by JaeWanSeol** [ossnu/osfall2017#3]
안녕하세요. 운영체제 강의를 수강중인 team4 설재완 입니다.

project0 진행중 문의사항이 었어서 이슈에 올립니다.

Wait until temp:90 .... 과 같은 (아마 device의 온도문제 같습니다)에러메시지가

기기를 연결하고 너무 빠른시간내에(5~15분내) 지속적으로 발생하는데 혹시 기계의 문제인지 아니면 해결방법이 있는지 궁금합니다.

감사합니다!

**Comment by pjbear1215** [comment]
안녕하세요, 302동 319-1호로 방문하시면 교체해드리도록 하겠습니다. 오시기 전에 연락주세요.
