### ISSUE TITLE
[proj3] Selector test 질문

### ISSUE THREAD

**Issue by dongyeob94** [ossnu/osfall2017#32]
안녕하세요 11조 임동엽입니다.

lock test를 하다가 궁금한점이 생겼는데요, selector 파일은 입력한 숫자부터 차례대로 높혀서 integer라는 파일에 저장하는 것으로 이해했습니다.

그런데, 예를 들어 ` ./selector 7492 ` 라는 명령어를 실행했을 때, integer라는 파일에 저장되는 숫자들이 궁금합니다.

integer 파일에 7492, 7493, 7494, 등이 모두 저장이 되는지, 혹은 마지막 숫자 하나만 저장이 되는지가 혼란스러운데요, 문서에는 후자로 설명이 되어있는 것 같은데 후자가 맞는건가요?

**Comment by pjbear1215** [comment]
후자가 맞습니다.
integer 파일은 단순히 selector와 trial이 정보를 주고받기 위해 사용하는 것입니다. 크게 의미있는 내용은 아니지만 후자처럼 구현하시는게 처리하기 쉬울 것 같습니다.

**Comment by dongyeob94** [comment]
감사합니다.

한가지 질문이 더 있는데요, 문서에 나와있는 테스트 결과에는 `./trial 0` 을 실행했을 경우, 결과가 7492, 7493, 7494 등의 결과가 나왔습니다.

이때 selector 실행 없이 `./trial 0`만 실행했을 경우 만약 integer에 7492라는 숫자 하나만 들어있었다면, 결과는 7492의 결과만 계속 반복해서 나와야 하는 것이 아닌지 헷갈립니다.

그리고 만약 문서에 나와있는 테스트 결과가 selector를 background 등에서 돌리고 있는 중이라고 가정한다면, write lock - write unlock - read lock - read unlock - write lock - ... 의 과정이 반복되는 중이라고 생각해도 되는건가요?

**Comment by pjbear1215** [comment]
1. 7492의 결과만 계속 나오는 것이 정상입니다.
2. 하나의 selector와 두개의 trial이 동시에 돌아가는 상황에서 어떤 프로세스가 먼저 lock을 시도하냐에 따라서 달라질 것 같습니다. write lock을 unlock하자마자 다시 write lock이 락을 잡을 수도 있고, read lock가 연달아서 성공할 수도 있습니다.
