### ISSUE TITLE
[proj3] trial identifier 질문

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#33]
안녕하세요? 1팀 이승현입니다.
trial의 identifier에 대해 여쭤보고 싶습니다.
프로젝트 공지일 때에 조교님께서
"trial을 실행할수록 identifier가 하나씩 증가하도록 예를 들어 trial-0, trial-1"이 되게 하라고 하신 것을 기억합니다, 문서에는 identifier를 argument로 받는다고 나와 있습니다. 그렇다면 꼭 trial이 실행되고 있는 개수대로 번호를 순서대로 부여할 필요는 없는 걸까요?
감사합니다.

**Comment by pjbear1215** [comment]
순서대로 자동으로 identifier를 부여할 필요는 없고, argument로 넘겨준 값을 identifier로 부여하면 됩니다. 이것은 단순히 출력할때 프로세스들을 쉽게 구분하기 위한 용도입니다.
