### ISSUE TITLE
[proj3] 테스트 결과 질문

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#34]
안녕하세요 1팀 이승현입니다.
`set_rotation`의 return value가 the number of process acquired the lock이라는 말을 보고
daemon에서 set_rotation으로 rotation을 update해줄 때마다 waiting process중에서 lock을 잡을 수 있는 것들을 잡게 해주는 방식으로 했는데요. 혹시 이런 식으로 하면 과제의 취지와 맞지 않나요?
selector와 trial을 돌릴 경우, daemon이 rotation update해주는 시간인 2초마다 selector와 trial이 standard output을 내놓고 있습니다. 우선 이렇게 하기는 했지만, 원래 문제의 취지대로라면, current rotation이 [0, 180]인 경우에는 계속 output이 나와야 하는 것이죠?(2초마다 나오는 것이 아니라)
감사합니다.

**Comment by pjbear1215** [comment]
>You should modify the set_rotation system call to unblock processes waiting on a lock that covers the new rotation. You should choose to allow either all blocked readers (may have different rotation ranges) to take the lock or a single blocked writer to take the lock. When a lock is taken by one or multiple processes, the processes are unblocked and return to user space. Your strategy to select either readers or a writer should consider fairness as a criteria.

spec에 언급되어 있듯이 말씀하신대로 처리해주는 것이 맞습니다. 

하지만 range는 맞지만 lock을 이미 다른 프로세스가 잡고 있어서 해당 lock이 풀리기를 기다리고 있는 프로세스들도 신경써주셔야 합니다.

이러한 프로세스들은 lock을 잡고 있는 프로세스가 lock을 release할 때 lock을 잡을 수 있도록 해줘야 합니다.

수업시간에 배우셨겠지만, Lock을 올바르게 구현하기 위해서는 다음 3가지 요소를 신경써주셔야 합니다.
1. Mutual exclusion
2. Progress (deadlock-free)
3. Bounded (starvation-free)

set_rotation() 시스템콜이 호출될 때만 lock을 처리한다면 2번 조건인 _Progress_ 를 만족시키지 못하게 됩니다.

만약 set_rotation( )이 호출이 되지 않는다면(degree가 변하지 않는다면), 아무도 lock을 잡고 있지 않은 상황에서도 어떤 쓰레드도 lock을 잡지 못할 것이기 때문입니다.

**Comment by yksnen11** [comment]
정말 감사합니다. 일단 여쭤본 문제는 조교님 말씀 덕분에 잘 해결을 할 수 있었습니다.
제공해주신 rotd를 조금 바꿔서 sleep(0.5)로 해보니까 `set_rotation`에서 lock을 잡고 놓는데 혼자 시간을 다 보내서 selector와 trial에서 결과가 띄엄띄엄(거의 안나옴) 나오는 현상이 있습니다. 물론 sleep(2)에서는 잘 나오고 있습니다. 그래서 여쭤보고 싶은데, 알람 주기를 어느 정도까지 생각해야 하나요? 지저분한 부분을 조금 정리하면 어느 정도까지는 개선될 것 같기 때문입니다.
감사합니다.

**Comment by JaeWanSeol** [comment]
안녕하세요. 4조입니다. 그러면 set_rotation()의 return 값은 the number of process acquired the lock가 아니라 degree의 변화에 의해 깨운 process의 수로 하면 되는것인가요?

**Comment by pjbear1215** [comment]
@yksnen11 제가 테스트해보지 않아서 확답을 드릴 수는 없지만, 이론적으로는 ``set_rotation``에 sleep이 조금이라도 들어가기만 한다면 selector와 trial이 lock을 시도하지 못할 이유는 없습니다.
 
아마 read lock, write lock을 수행하실 때 degree lock을 풀었다 놨다해서 ``set_rotation``때문에 selector와 trial이 진행이 안되는 것처럼 보이네요.  

기본 셋팅에서 결과가 잘나오기만 하면 될 것 같습니다.

**Comment by pjbear1215** [comment]
@JaeWanSeol degree의 변화에 의해 깨어나서 lock을 잡는데 성공한 프로세스의 갯수를 return값으로 해주시면 됩니다.

**Comment by JaeWanSeol** [comment]
답변 감사합니다. 아울러 추가질문이있는데요, 다음의 상황에서는 어떻게 처리해야 하는지 궁금합니다.
예를들어 9초인 순간에 현재 device degree는 30이고 writer A가 30~80구간에 lock을 잡고,
10초인 순간에 device degree가 60으로 바뀌는데, 잠들어 있던 모든 프로세스가 모두 60~90구간에 lock을 잡으려고 한다면, A로 인해서 아무도 깨어나지 말아야 하는 것인가요? 
그렇다면 또한 만약 10.2초인 순간에 writer A가 unlock을 한다면 잠들어있던 process들이 lock을 잡으려고 시도할 수 있을텐데, 앞의 10초인 순간에서 아무것도 깨우지 않았으므로 1.8초는 버리는(?) 시간이 되어야하나요?

질문의 의도는 degree가 바뀌는 순간에 lock을 바로 잡을 수 있는 process만 깨우는 것이 아니라 degree를 포함하는 lock을 잡으려는 애들은 모두 깨워준다면, 2초 내에 누군가 unlock을 한다면 그 자리를 채울 수 있지 않을까 하는 의도입니다!

**Comment by pjbear1215** [comment]
@JaeWanSeol 이건 구현을 어떻게 했냐에 따라 다를 것 같습니다. lock을 잡을 수 있도록 깨울 때, degree를 만족하는 모든 프로세스들을 깨우는 방법도 있을 것이고, degree를 만족하는 애들 중에서 실제로 lock을 잡을 순서에 있는 프로세스들만 깨울 수도 있을 것 입니다.

unlock 이벤트가 발생했을 때도 조건에 맞는 애들을 깨워주면 되지않을까요?
