### ISSUE TITLE
[proj4] uninitialized location 질문

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#38]
안녕하세요 1팀 이승현입니다.
"from system boot to the first `sys_gps_location` system call, location is arbitrary but should meet the criteria"라고 적혀있습니다만, (0.000000, 0.000000)으로 initialize해도 무방한 것이죠?
감사합니다.

**Comment by pjbear1215** [comment]
네 (0.000000, 0.000000)도 조건에는 만족하므로 상관없습니다.

**Comment by yksnen11** [comment]
감사합니다^^
