### ISSUE TITLE
[proj4] accuracy 질문

### ISSUE THREAD

**Issue by yksnen11** [ossnu/osfall2017#39]
안녕하세요 1팀 이승현입니다.
accuracy의 가능 범위에 대해 여쭤보고 싶은 것이 있습니다.
location based authorization할 때에 accuracy는 두 location간의 error를 tolerate하기 위한 값으로 이해했습니다.

예를 들어서 9999999999m는 accuracy의 가능한 값 중에 하나입니다.
반면, accuracy가 gps 상의 오류를 tolerate하기 위한 값이라면
9999999999m와 같은 큰 값으로 gpsupdate시켜주는 건 조금 이상한 상황이라고도 생각됩니다.

fpu emulate하는 법을 몰라서 int만으로 distance와 accuracy를 비교하려고 했습니다만,
북반구와 남반구의 두 지점이 예를 들어서 latitude difference가 150정도라면, meter unit으로 적어도 10000000m는 차이가 나고, cos, sin을 쓰지 않고 제곱해서 근사하면 int 표현범위를 넘어버려서 제대로 된 비교가 안 됐습니다. 한편 long long int에 division이 안돼서 do_div()를 쓰고 있는데 속도가 느리다는 부작용도 있는 것 같습니다.

accuracy의 가능범위는 제한이 있는지 여쭤보고 싶습니다.(있다면 위의 문제가 해결되기 때문에 궁금합니다.) 그리고 accuracy를 기준으로 비교할 때 비교가 어느 정도로 정확해야 하나요? 예를 들어서 주어진 latitude, longitude의 실제 지구상 거리는 2010m이고 accuracy합이 2000m여서 사실 read가 금지되어야 하는데 근사 결과 1995m이라 허용한 경우 문제가 되는지 여쭤보고 싶습니다.

감사합니다.

**Comment by pjbear1215** [comment]
일반적으로 Accuracy값을 그렇게 극단적으로 크게 줄 이유는 없을 것 같습니다. 
일반적인 GPS의 오차범위수준이 수십미터 정도인 것으로 알고 있습니다. 
과제에서 의도한 건 301동에서 만든 파일을 302동에서 접근하지 못하도록 막는 정도의 정확도입니다.

그리고 두 GPS 좌표의 거리를 구할 때 반드시 정확한 값을 구할 필요는 없습니다. 말씀하신대로 적당히 근사값을 구하여 할수도 있을 것이고, 어느 정도 이상 차이가 나는 것을 안다면 굳이 거리계산없이도 파일에 대한 접근을 차단할 수도 있을 것입니다.

**Comment by yksnen11** [comment]
감사합니다^^
