### ISSUE TITLE
안녕하세요 Project 0 진행 중 문의입니다.

### ISSUE THREAD

**Issue by dongyeob94** [ossnu/osfall2017#5]
안녕하세요.

이번 Project 0 을 진행하던 도중 막히는점이 있어서 질문드립니다.

진행 도중 debug console을 띄우는 것에서 문제가 생겼는데,

![error](https://user-images.githubusercontent.com/31842674/30510580-03ae2250-9b02-11e7-92af-0f10ac5936c7.PNG)

위의 그림과 같이 device의 이름을 알아낸 후, debug console 창을 띄우려는 데 screen이 확인되지 않는다고 뜹니다.

우선 이 과정을 건너뛴 후, build 부터 실행시킨 결과, build는 잘 작동이 되었습니다.

여기까지 과정에서 무엇에 문제가 있어서 해결이 안되는 것인지 알려주시면 감사하겠습니다.

**Comment by pjbear1215** [comment]
개발 환경을 알려주시기 바랍니다.
스크린샷상으로 봤을때는 artik 장치가 제대로 가상머신에 연결되지 않은 것으로 보입니다.
USB Filter 문제를 한번 확인해보시기 바랍니다.
tty0 말고 다른 장치 이름이 있어야 합니다.
build의 경우는 artik 장치와 독립적으로 가상머신 안에서 커널 이미지를 만드는 것이기 때문에 prebuilt package를 제대로 설치하셨다면 순서는 상관없습니다.

**Comment by dongyeob94** [comment]
개발환경은 ubuntu-16.04.3 버전입니다.

그리고 USB Filter 문제를 확인하라는 것이 무엇인지 한번더 설명해주실 수 있으신가요?

![image](https://user-images.githubusercontent.com/31842674/30510913-ce3dcba0-9b08-11e7-8c3a-46a9b5363432.png)

그리고 ls /dev/ 의 결과는 위와 같습니다.

감사합니다.

**Comment by pjbear1215** [comment]
Virtual Box로 ubuntu VM을 만드신 걸로 보이는데 virtual box가 설치되어있는 호스트 머신의 운영체제는 무엇인가요? 그것도 ubuntu인가요?

만약 윈도우라면 [링크](https://github.com/ossnu/osfall2017/blob/master/doc/SetupOnWindows.md)를 참조하시기 바랍니다. ([Project0](https://github.com/ossnu/osfall2017/blob/master/doc/Project0.md#development-environment) 문서에 호스트 머신의 운영체제에 따른 설정 방법이 나와있습니다.)

기본적으로 artik 장치는 물리적으로 Host 머신에 usb로 연결되어 있기때문에 아무런 설정을 하지 않으면 Guest 머신에서는 보이지 않습니다. 

Host 머신에서 해당 장비가 보인다면, Host 머신에서 `PuTTY` 또는 `console`를 통해 artik에 접근할 수 있습니다. 반드시 Guest 머신에서 `console` 명령어를 통해 artik에 접근해야하는 것은 아닙니다.

장치가 제대로 인식이 되는지 usb를 뽑았다 꼈다 해보시기 바랍니다. 장치 인식만 되면 해결될 문제로 보입니다.

**Comment by dongyeob94** [comment]
USB 설정을 안했던것 같습니다.

알려주셔서 감사합니다!

**Comment by melodyjs** [comment]
저도 질문 하나 드립니다 ㅜㅜ

<img width="570" alt="2017-09-17 12 49 51" src="https://user-images.githubusercontent.com/22289986/30513673-38d05562-9b42-11e7-8ee9-9a0f1d97c306.png">

<img width="733" alt="2017-09-16 11 31 58" src="https://user-images.githubusercontent.com/22289986/30513675-3d73f25e-9b42-11e7-87f5-e310b811ea96.png">

thordown까지 한 상태에서 flash를 입력했는데 

저 상태에서 설치가 안되는데 무슨 문제일까요 ㅠㅠ

혹시나 다운로드 속도 때문인가 해서 2시간정도 기다려봤는데도 설치가 안되네요

**Comment by pjbear1215** [comment]
@melodyjs 실습때 제 맥북에서도 비슷한 일이 있었는데, usb 연결 문제입니다.

USB-A to USB-A 케이블이 제대로 연결되었는지 확인해보시고, 컴퓨터의 다른 포트에도 꽂아보시기 바랍니다.

터미널에서 `lsusb`를 쳤을 때, 새로운 장치가 뜨는지 확인해보시면 됩니다.

제 경우에는 VitualBox가 아니라 VMware Workstation을 사용했었는데, 처음에는 뜨지않다가 `flash`를 치고나면 "가상머신에 usb를 연결하시겠습니까?"라는 창이 떴고, "예"를 눌러야 연결이 되면서 장치에 커널 이미지가 업로드되었던 것으로 기억합니다.

**Comment by melodyjs** [comment]
늦은 시간에 답변 감사드립니다.

저도 맥북을 사용하고 있는데 혹시 usb를 연결하면 파인더 기기목록에 떠야하는건가요?

제 컴퓨터에는 연결을 해도 뜨지가 않네요 ㅠㅠ

**Comment by pjbear1215** [comment]
@melodyjs 장비들이 학교에 있어서 지금은 확인이 불가능하네요 ㅠㅠ

저같은 경우에는 맥북에 달려있는 2개의 usb port를 바꿔서 꽂아보고 하다보니, 어느 순간 인식이 됐었습니다.

VMware Workstation같은 경우에는 호스트 머신에 USB 장치가 연결될 경우, 자동으로 팝업 창을 띄워서 가상 머신에 해당 장치를 연결할 거냐고 물어보는데, VitualBox는 확실하지 않네요 ㅠㅠ.

USB filter 관련 부분 설정 제대로 됐는지 [링크](https://github.com/ossnu/osfall2017/blob/master/doc/SetupOnMac.md#adding-usb-forwarding-rule) 확인해주세요.

**Comment by melodyjs** [comment]
<img width="651" alt="2017-09-17 1 37 42" src="https://user-images.githubusercontent.com/22289986/30514037-f95c367e-9b48-11e7-9d63-df5a51bf1811.png">

답변 감사합니다. 

확인해보니 USB 필터도 이름 복사 붙여넣기로 넣어서 제대로 들어가있습니다 ㅜㅜ

USB 위치를 바꿔도보고, 컴퓨터도 재부팅 해서 해봤는데 flash가 계속 안되네요.

혹시 월요일에 직접 가지고 가도 될까요 ㅠㅠ

**Comment by pjbear1215** [comment]
@melodyjs 네 오시기 전에 미리 연락주시기 바랍니다. (010-9270-7442)

**Comment by melodyjs** [comment]
<img width="726" alt="2017-09-17 1 42 33" src="https://user-images.githubusercontent.com/22289986/30514084-9c0ab328-9b49-11e7-9036-472eec854b21.png">

아... 신기하게도 포기하려던 찰나에 갑자기 되는군요...

어떻게 갑자기 된건진 모르겠지만 여튼 성공했습니다. 감사합니다 ㅠㅠ
