### ISSUE TITLE
프로젝트 스펙 문의입니다.

### ISSUE THREAD

**Issue by JaeWanSeol** [ossnu/osfall2017#7]
안녕하세요. os-team4 입니다.
스펙 관련 문의가 있어서 issue에 남깁니다.

1. https://github.com/ossnu/osfall2017/blob/master/doc/Project1.md
위의 프로젝트1 문서를 보면, 출력예시에 systemd부터 출력하고, swapper\0라는 프로세스는 출력하지않는데
그렇다면 prinfo buf에 swapper\0프로세스는 넣지 않아도 되는 것인가요?
즉 첫 task의 pid가 0부터인가요 1부터 인가요??

2. return value에 대한 질문입니다. 
(a)만약 *nr값을 200을 주고, 현재 돌고있는 프로세스의 개수가 365개 라면
ptree system call이 끝난 후에 nr에는 200, return value에는 365를 주는것이 맞나요?
(b)만약 *nr값을 400을 주고, 현재 돌고있는 프로세스의 개수가 365개 라면
ptree system call이 끝난 후에 nr에는 365, return value에는 365를 주는것이 맞나요?

감사합니다.

**Comment by pjbear1215** [comment]
1. swapper의 경우 일반적인 프로세스가 아니라 해당 CPU 코어가 idle상태(수행할 프로세스가 하나도 없을 경우)일때를 나타내는 특별한 프로세스입니다. 스펙은 따로 정해져있지않고, swapper를 출력하셔도 되고 빼셔도 됩니다. 채점 결과에 영향은 없습니다. `README.md`에 명시만 해주시기 바랍니다.

2. 기본적으로 시스템콜의 return value는 성공할 경우 0, 실패할 경우 -1이며, 실패할 경우 error code는 errno에 저장됩니다. 따라서 시스템콜을 통해 결과를 받아오기 위해서는 유저에서 넘겨준 버퍼를 활용해야만 합니다. 

    (a) 예외처리 방법에 따라 다르게 구현할 수 있을 것 같습니다. 넘겨준 *nr값보다 현재 돌고있는 프로세스의 개수가 많을 때 에러를 발생시켜 유저에게 더 큰 버퍼를 할당하라고 강제할 수도 있고, 넘겨준 *nr값만큼만 프로세스 정보를 가져올 수도 있을 것입니다. 

    (b) 시스템콜 후에 넘겨받는 *nr값에는 버퍼에 실제 들어가있는 프로세스 정보 수가 들어가있어야 테스트 프로그램에서 올바르게 출력할 수 있을 것입니다.
