### ISSUE TITLE
[Project1, team4] Error Handling 질문

### ISSUE THREAD

**Issue by Jim741305** [ossnu/osfall2017#8]
안녕하세요 조교님,

OSteam4입니다. 
EINVAL, EFAULT 등 errno 처리에 관한 질문입니다. 
지난번에 조교님이 해주신 답변을 읽어보고 저희끼리 고민해본 결과,
에러가 발생할 경우 System Call 함수의 return 값은 -1이며, errno 값을 EINVAL, EFAULT 등으로 update해야 한다고 결론내렸습니다.  

하지만 커널 내에 있는 system call 함수에서 errno.h 헤더파일을 추가하여 errno 변수에 접근하려고 했으나, 커널 내에서는 errno 변수를 업데이트 하지 못하는 것으로 확인되었습니다. 

errno 변수에 어떤 방식으로 접근해야 하나요?
그리고 저희가 위에 내린 결론이 맞는 것인가요?

갑사합니다.

**Comment by JaeWanSeol** [comment]
아울러서 공식 office hour시간이 혹시 정해져 있나요?

**Comment by pjbear1215** [comment]
@Jim741305 시스템콜을 핸들링하는 커널 내부의 함수에서는 errno값을 직접 접근할 필요없이 
`return -EINVAL;`
`return -EFAULT;`
이런 식으로 return 값으로 반환하시면 됩니다.
유저 프로그램에서 해당 시스템콜이 왜 실패했는지 알고 싶을 때, errno 출력을 통해 확인할 수 있습니다.

**Comment by pjbear1215** [comment]
@JaeWanSeol 공식 Office Hour는 따로 정해져있지 않고, 될 수 있으면 Issue 게시판을 활용해주시기 바랍니다. Issue 게시판을 통해 해결이 안될 경우에는 따로 시간을 정해서 방문해주시면 됩니다.
