### ISSUE TITLE
push에 관해서 질문있습니다.

### ISSUE THREAD

**Issue by qwerty3535** [ossnu/osfall2017#9]
보드에 test program을 push하려고 하는데 에러가 발생합니다.
아래와 같이 test program을 compile하고
qwerty35@qwerty35:~/workspace/OS/test_ptree$ arm-linux-gnueabi-gcc -I /home/qwerty35/workspace/OS/linux-3.10-artik/include test.c -o test

이를 아래와 같이 push하려는데 connection error가 나옵니다.
qwerty35@qwerty35:~/workspace/OS/test_ptree$ push test /root/test
error: target not found
fatal: failed to open sync channel: connection fails

제가 제대로 한 것이 맞는지 아니면 다른 이상이 있는건지 궁금합니다.

또한 usb연결이 잘 안된것인지 Project0에서 console에 

direct_set_debug.sh --sdb-set

을 입력하면 

![1](https://user-images.githubusercontent.com/31840685/30748839-752bdf64-9fec-11e7-9b4c-afb600bf462a.png)

와 같이 나옵니다. 어떤 문제가 있는 것인가요?

환경은 데스크톱, Ubuntu 14.04이고 가상머신은 쓰지 않았습니다.

**Comment by pjbear1215** [comment]
sdb 자체는 enable상태로 바뀐것으로 보입니다.
현재 console에서 뜨는 에러들은 실제 프로젝트 진행하는데 문제가 되지 않는 에러들이라 신경쓰지 않으셔도 될 것 같습니다.
우선 터미널에서 `sdb devices`를 입력하고, 장치가 제대로 연결이 됐는지 확인해보시기 바랍니다.
구글에서 가져온 그림이라 똑같지 않겠지만, 아래와 같이 `List of devices attached` 아래에 artik 장치가 보여야합니다.
<img width="300" alt="screenshot of google chrome 23-09-2017 6-33-48 pm" src="https://user-images.githubusercontent.com/5715138/30771961-c276e894-a08d-11e7-9769-8ccf18b4ff18.png">

**Comment by qwerty3535** [comment]
![1](https://user-images.githubusercontent.com/31840685/30778864-144efaca-a11b-11e7-8978-37d798103502.png)

list of devices에 artik장비가 잡히지 않아서 그런 것 같습니다. 이럴 경우에는 어떻게 해야하나요?

usb포트를 다르게 해도 artik이 잡히지 않습니다.

**Comment by pjbear1215** [comment]
프로젝트 0은 잘 되셨었나요?
`sdb kill-server`
`sdb start-server`
`sdb devices`
를 해도 똑같은지 확인해주시기 바랍니다.

**Comment by qwerty3535** [comment]
프로젝트 0은 flash를 해서 success가 나오는 것을 확인했습니다.

하지만 sdb kill, start를 해도 똑같이 연결이 안되고 있습니다.

![1](https://user-images.githubusercontent.com/31840685/30780522-88647968-a147-11e7-80ec-3d24637611e9.png)

**Comment by pjbear1215** [comment]
`console`을 통해 artik에 root로 로그인 하신 뒤, 
`direct_set_debug.sh --sdb-set` 를 수행하시면 artik 장치의 usb(USB-A to USB-A)가 연결되어야 합니다.

실제로 USB-A to USB-A를 연결하지 않고 테스트해봐도 `usb_mode usb: slp_multi_usbL enable SUCCESS 'sdb' SDB enabled`는 똑같이 console창에 출력되는 것 같습니다.

USB-A to USB-A가 제대로 연결되어 있다면, sdb를 enable시킨 후에
터미널에 `lsusb` 명령어를 치면 `Samsung Electronics Co., Ltd Galaxy (MTP)`가 보여야 합니다.

Project 0에서 했었던 `thordown` & `flash`는 지금은 되는 상태인지 한번 확인해주시기 바랍니다.

![screenshot from 2017-09-24 01-07-28](https://user-images.githubusercontent.com/5715138/30780672-7d126d5a-a14b-11e7-98c6-c1b53623c590.png)

**Comment by qwerty3535** [comment]
![1](https://user-images.githubusercontent.com/31840685/30781020-af1154a4-a152-11e7-83e8-8e545b562385.png)

어떻게 됐는지는 모르겠지만 인식이 됐습니다.

주말에 봐주시느라 감사합니다.
